name: generate breakout svg

on:
  schedule:
    - cron: "0 */24 * * *" # Chạy mỗi ngày
  workflow_dispatch: # Chạy thủ công

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Breakout SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}

      - name: Move SVGs
        run: |
          mkdir -p images
          mv output/light.svg images/breakout-light.svg
          mv output/dark.svg images/breakout-dark.svg

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/breakout-light.svg images/breakout-dark.svg
          git commit -m "Update breakout SVGs" || echo "No changes"
          git push
